print("Анкета пациента в больнице.")
b = input("Укажите ваше ФИО: ")
c = input("Ваша дата рождения: ")
d = input("Укажите ваш адрес проживания: ")
e = input("Каков ваш рост? ")
m = input("Каков ваш вес? ")
print(b)
print(c)
print(d)
print(e)
print(m)